# Hardware configuration for spectre.
# Generated by nixos-generate-config, adapted to dendritic format.
{
  nixpkgs.config.allowUnfreePackages = [
    "firmware-linux-nonfree"
    "amd-microcode"
    "amd-ucode"
  ];

  configurations.nixos.spectre.module =
    {
      config,
      lib,
      ...
    }:
    {
      nixpkgs.hostPlatform = "x86_64-linux";

      hardware.enableRedistributableFirmware = true;

      boot = {
        initrd = {
          availableKernelModules = [
            "xhci_pci"
            "ahci"
            "sr_mod"
            "virtio_pci"
            "virtio_blk"
          ];
          kernelModules = [ "amdgpu" ];
        };
        kernelModules = [ ];
        extraModulePackages = [ ];
      };

      networking.useDHCP = lib.mkDefault true;

      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
