# Hardware configuration for flatmate.
# Generated by nixos-generate-config, adapted to dendritic format.
{
  nixpkgs.config.allowUnfreePackages = [
    "firmware-linux-nonfree"
    "intel-microcode"
  ];

  configurations.nixos.flatmate.module =
    {
      config,
      lib,
      ...
    }:
    {
      nixpkgs.hostPlatform = "x86_64-linux";

      hardware.enableRedistributableFirmware = true;

      boot = {
        initrd = {
          availableKernelModules = [
            "xhci_pci"
            "nvme"
          ];
          kernelModules = [ ];
        };
        kernelModules = [ "kvm-intel" ];
        extraModulePackages = [ ];
      };

      networking.useDHCP = lib.mkDefault true;

      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
