_: {
  den.aspects.apps.messaging.vesktop.homeManager = _: {
    programs.vesktop.enable = true;

    # Login token and Vencord settings. The Stylix-generated theme under
    # .config/vesktop/themes is regenerated by activation, so it does not need
    # its own entry.
    home.persistence."/persist".directories = [ ".config/vesktop" ];
  };
}
