# Hardware configuration for endgame.
# Generated by nixos-generate-config, adapted to dendritic format.
{
  nixpkgs.config.allowUnfreePackages = [
    "firmware-linux-nonfree"
    "amd-microcode"
    "amd-ucode"
  ];

  configurations.nixos.endgame.module =
    {
      config,
      lib,
      ...
    }:
    {
      nixpkgs.hostPlatform = "x86_64-linux";

      hardware.enableRedistributableFirmware = true;

      boot = {
        initrd = {
          availableKernelModules = [
            "nvme"
            "xhci_pci"
            "ahci"
            "usb_storage"
            "usbhid"
            "sd_mod"
            "hid"
          ];
          kernelModules = [ "amdgpu" ];
        };
        kernelModules = [
          "kvm-amd"
          "amdgpu"
        ];
        extraModulePackages = [ ];
      };

      networking.useDHCP = lib.mkDefault true;

      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
